### ISSUE TITLE
In process EventBus <=> MQTT bridge

### ISSUE THREAD

**Issue by philrykoff** [GruppoFilippetti/vertx-mqtt-broker#10]
Hey, thanks for this library :+1: 

I'd like to extend a vertx application with MQTT support, which is why I would to start the broker like this:

```
		deploymentOptions.setConfig(
			new JsonObject().put("broker", 
				new JsonArray().add(new JsonObject().put("tcp_port", 1883))
			)
		);

		vertx.deployVerticle(MQTTBroker.class.getName(), deploymentOptions);
```

Do I also need to configure MQTT EventBus client/server bridges in order to communicate with my other MQTT clients, or can I somehow directly send messages to them?

From what it looks like in `MQTTSession`, each connected MQTT client subscribes to the EventBus address "io.github.giovibal.mqtt", so can I send messages to that address in order to communicate with the MQTT clients? Which format do they need to have? Should I subscribe to that address in order to fetch incoming messages?

Thanks :smile: !

**Comment by giovibal** [comment]
Thank you for partecipation!
You should connect all mqtt clients through port 1883, but not use EventBus directly, because pub/sub functionality is not directly mapped into EventBus.
