### ISSUE TITLE
Vert.x MQTT Server

### ISSUE THREAD

**Issue by vietj** [GruppoFilippetti/vertx-mqtt-broker#11]
In Vert.x 3.4 we will provide an MQTT Server implementation (https://github.com/vert-x3/vertx-mqtt-server). Perhaps it could be re-used by this MQTT Broker implementation ?

**Comment by ppatierno** [comment]
I think that it could simplify the current MQTT broker implementation, leaving all the wire protocol with codec/encodec to the underlying Vert.x MQTT server and developing the broker logic on top of it.

**Comment by arden** [comment]
when is vertx 3.4 released?

**Comment by vietj** [comment]
@arden there will be a 3.4 first beta soon, and the final release is expected in the first quarter 2017

**Comment by arden** [comment]
https://github.com/vert-x3/vertx-mqtt-server
has been released a 3.4 beta version

**Comment by giovibal** [comment]
Hi all, I agree with @arden 
I'm valuating vert.x official implementation to replace all mqtt protocol stuff, this can speed up to mantain of next versions of mqtt (v 5 and so on).
There are some features we need to mantain like multi tenancy, bidirectional bridge per tenant, clustering etc...
I hope to commit something interesting about this integration next time

**Comment by ppatierno** [comment]
@giovibal great to know ! Ping us if you have feedback on that.

FYI @arden the 3.4.0 Beta 1 version is out, here some information about it : 

http://vertx.io/blog/vert-x-3-4-0-beta1-release/

**Comment by easykoala** [comment]
two mqtt client can not communicate each other using vertx mqtt server,why?

**Comment by ppatierno** [comment]
@easykoala the Vertx MQTT server is ... a server not a full MQTT broker. It provides handling all the underlying protocol infrastructure and communication with remote endpoint but it doesn't implement a full broker logic. A broker can be build on top of it.

**Comment by andsel** [comment]
I think calling a thing MQTT server and it's not properly a broker is a bit
misleading, it's just an endpoint?

**Comment by easykoala** [comment]
oh, I see thx @ppatierno

**Comment by ppatierno** [comment]
@andsel a broker is more than a server because it's an "intermediary" between producer/consumer, so for handling their messages exchange (i.e. it's an intermediary like a stock broker between seller and buyer). In Vert.x even the HTTP server provides you a way for just handling connection/requests/responses with remote HTTP clients but you have to write the logic on top of it.

**Comment by andsel** [comment]
Ok I understood it's a Vert.x server, I meant server in the same sense as
defined in MQTT specifications:

"

Server:
A program or device that acts as an intermediary between Clients which
publish Application Messages and Clients which have made Subscriptions. A
Server

·         Accepts Network Connections from Clients.

·         Accepts Application Messages published by Clients.

·         Processes Subscribe and Unsubscribe requests from Clients.

·         Forwards Application Messages that match Client Subscriptions.
"

Thaks @ppatierno for the clarification

 Andrea

**Comment by ppatierno** [comment]
@andsel for example ... in the MQTT spec, I would have called it ... broker :-) 
If you search for MQTT on Google you'll find that all implemented "servers" are named brokers (i.e. HiveMQ, Mosquitto, VerneMQ, ...)

**Comment by Andy320** [comment]
Thank you all first. And I have several questions here.

1. @vietj Now vertex is 3.4.2, I wonder if the websocket is already supported by vert.x mqtt server officially?

2. @giovibal @ppatierno Could you please share some demos with me about how to use this broker with  websocket?

thanks

**Comment by giovibal** [comment]
You can use this library https://eclipse.org/paho/clients/js/
The broker config can start a port for websocket, for example 11884, and you can use this broker-uri to connect: ws://host:8080 or wss://host:11884 if you use ssl.
See example configuration in file "config.json"... there is a section like this below that enable websocket on that port:
```
{
    "tcp_port": 11884,
    "retain_support": true,
    "websocket_enabled": true,
    "websocket_subprotocols": "mqtt,mqttv3.1",
    "authenticator_address": "mqtt.authenticator.oauth2"
}
```

**Comment by ppatierno** [comment]
@Andy320 the Vert.x MQTT server doesn't support websocket in the 3.4.2. For now there is no plan to support that.
