### ISSUE TITLE
subscribe Topic "mqtt/bbb/#" and publish "mqtt/bbb", but receive nothing.

### ISSUE THREAD

**Issue by easykoala** [GruppoFilippetti/vertx-mqtt-broker#17]
public static Topic[] topics = {   
            new Topic("mqtt/aaa", QoS.EXACTLY_ONCE),   
            new Topic("mqtt/bbb/#", QoS.AT_LEAST_ONCE),  
            new Topic("mqtt/ccc", QoS.AT_MOST_ONCE),
            new Topic("/inode/mychannel", QoS.AT_LEAST_ONCE)};  
            ------------------
             final FutureConnection connection = mqtt.futureConnection();  
                connection.connect();  
                connection.subscribe(topics);  
    		JsonObject jo = new JsonObject().put("act", "post").put("info", new JsonObject().put("name", "wangzb").put("nickname", "easykoala").put("mobile", "13606012346"));
    		connection.publish("mqtt/bbb", jo.toString().getBytes("utf-8"), QoS.AT_LEAST_ONCE, false);

            ------------------
            but I receive nothing.

**Comment by giovibal** [comment]
Can you send a complete "test" code sample, with publish  and other stuff, to let me run it quickly ?
We'll try to evaluate as soon as possibile.

**Comment by giovibal** [comment]
If you subscribe to mqtt/bbb/# you must publish to mqtt/bbb/something and not to mqtt/bbb only.
This is a standard behaviour of mqtt protocol.
